### ISSUE TITLE
Blog Subscribe Language / Flow

### ISSUE THREAD

**Issue by Left47** [BrightCrowd/bc-blog#1]
Feature Branch:
`feature/signup`

Language Updates
- [x] Sidebar Language

UX Cleanup
- [x] subscribed.html: [mockup](https://docs.google.com/presentation/d/1drZjMVQRHkahVZ4icxIwgh8cQAuzRV0NIDcWZOUpy6s/edit#slide=id.g3cef90bab2_0_63)
- [x] index.html: [mockup](https://docs.google.com/presentation/d/1drZjMVQRHkahVZ4icxIwgh8cQAuzRV0NIDcWZOUpy6s/edit#slide=id.g3cef90bab2_0_207)

**Comment by kmarkfield** [comment]
@Left47 I've pushed the styles for this.  The sidebar language is hardcoded right now.
